name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Change to Backend Directory
      run: cd Backend
      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Node.js and Install Dependencies
      uses: actions/setup-node@v3
      with:
        node-version: v16.13.0
        cache: 'npm'

    - name: Install Backend Dependencies
      run: npm ci

    - name: Run Backend Tests
      run: npm test

  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Change to Frontend Directory
      run: cd Frontend
      
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js and Install Dependencies
      uses: actions/setup-node@v3
      with:
        node-version: v16.13.0
        cache: 'npm'

    - name: Install Frontend Dependencies
      run: npm ci

    - name: Run Frontend Tests
      run: npm test
